<?php

return [
    'MANUSU' => 'Mantener usuarios',
    'MANPER' => 'Mantener perfiles',
    'MANCOL' => 'Mantener centros',
    'MANSOST' => 'Mantener sostenedores',
    'MANTRA' => 'Mantener personal',
    'REMEMI' => 'Emitir liquidaciones de sueldo',
    'MANISAPRE' => 'Mantenedor de cotizaciones de salud',
    'MANAFPTR' => 'Mantener AFPs trabajadores',
    'CONPREVAFP' => 'Informe previsional AFP',
    'MANBODESCOL' => 'Mantenedor de bonos y descuentos por centro',
    'MANBODESTRA' => 'Mantenedor de bonos y descuentos trabajador',
    'CONPREVISAPRE' => 'Informe previsional ISAPRES',
    'MANIECO' => 'Mantenedor de indices económicos',
    'MANBODESGEN' => 'Mantenedor de bonos y descuentos generales',
    'MANLIQ' => 'Mantenedor de plantilla de liquidaciones',
    'MANIMREN' => 'Mantenedor de valores para impuesto a la renta',
    'MANASIGFAM' => 'Mantenedor de valores para asignación familiar',
    'MANLIC' => 'Mantenedor de licencias medicas',
    'MANAFP' => 'Mantenedor de afps',
    'MANISAPRETR' => 'Mantenedor de isapres',
    'MANINAS' => 'Mantendedor de inasistencias',
    'VERHISTORIAL' => 'Ver historial',
    'CCOST' => 'Centro de costo',
    'PLANREMU' => 'Planilla de remuneraciones',
    'MANICOM' => 'Mantenedor de indices de corrección monetaria',
    'CERTREMU' => 'Certificado de remuneraciones',
];
