<?php

use App\Models\Worker;

return [
    'bonuses'    => [
        [
            'title'       => 'Asignacion Voluntaria',
            'type'        => 3,
            'taxable'     => 0,
            'imputable'   => 0,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'D',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'RBMN',
            'type'        => 1,
            'taxable'     => 0,
            'imputable'   => 0,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'C',
            'months'      => null,
            'amount'      => 7824,
        ],
        [
            'title'       => 'Ley 19410',
            'type'        => 1,
            'taxable'     => 0,
            'imputable'   => 0,
            'is_bonus'    => 0,
            'factor'      => 80,
            'application' => 'H',
            'months'      => null,
            'amount'      => 795260,
        ],
        [
            'title'       => 'Ley 19933',
            'type'        => 1,
            'taxable'     => 0,
            'imputable'   => 0,
            'is_bonus'    => 0,
            'factor'      => 80,
            'application' => 'H',
            'months'      => null,
            'amount'      => 2231533,
        ],
        [
            'title'       => 'Perfeccionamiento',
            'type'        => 1,
            'taxable'     => 0,
            'imputable'   => 0,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'D',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'Prestamo Social Caja los heroes',
            'type'        => 3,
            'taxable'     => 0,
            'imputable'   => 1,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'D',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'Prestamo Social Caja los Andes',
            'type'        => 3,
            'taxable'     => 0,
            'imputable'   => 1,
            'is_bonus'    => 1,
            'factor'      => 100,
            'application' => 'D',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'Colegio de profesores',
            'type'        => 1,
            'taxable'     => 0,
            'imputable'   => 1,
            'is_bonus'    => 1,
            'factor'      => 1,
            'application' => 'I',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'Cuenta Ahorro Caja los Andes',
            'type'        => 3,
            'taxable'     => 0,
            'imputable'   => 1,
            'is_bonus'    => 1,
            'factor'      => 100,
            'application' => 'D',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'Fundacion Lopez Perez',
            'type'        => 3,
            'taxable'     => 0,
            'imputable'   => 1,
            'is_bonus'    => 1,
            'factor'      => 100,
            'application' => 'D',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'Desempeño dificil',
            'type'        => 3,
            'taxable'     => 0,
            'imputable'   => 1,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'H',
            'months'      => null,
            'amount'      => 466607,
        ],
        [
            'title'       => 'Otros',
            'type'        => 2,
            'taxable'     => 1,
            'imputable'   => 1,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'D',
            'months'      => null,
            'amount'      => 0,
        ],
        [
            'title'       => 'Ley 19464',
            'type'        => 2,
            'taxable'     => 0,
            'imputable'   => 1,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'H',
            'months'      => null,
            'amount'      => 246661,
        ],
        [
            'title'       => 'UMP',
            'type'        => 1,
            'taxable'     => 0,
            'imputable'   => 0,
            'is_bonus'    => 0,
            'factor'      => 100,
            'application' => 'T',
            'months'      => null,
            'amount'      => 663,
        ],
    ],

    'operations' => [
        ['IMPONIBLEEIMPUTABLE', 1,
            NULL, null, 0, 0, 0, '111111111111'],
        ['TOTALAPAGAR', 1, 'TOTALHABERES - TOTALDESCUENTOS', null, 0, 0, 0, '111111111111'],
        ['TOTALAPAGAR', 2, 'TOTALHABERES - TOTALDESCUENTOS', null, 0, 0, 0, '111111111111'],
        ['AFP', 1, 'COTIZACIONAFP / 100 * RENTAIMPONIBLE', null, 0, 0, 0, '111111111111'],
        ['SALUD', 1, 'COTIZACIONISAPRE * RENTAIMPONIBLE / 100', null, 0, 0, 0, '111111111111'],
        ['AFP', 2, 'COTIZACIONAFP / 100 * RENTAIMPONIBLE', null, 0, 0, 0, '111111111111'],
        ['SALUD', 2, 'COTIZACIONISAPRE * RENTAIMPONIBLE / 100', null, 0, 0, 0, '111111111111'],
        ['DESCUENTOSLEGALES', 1, 'AFP + SALUD + SEGUROCESANTIA', null, 0, 0, 0, '111111111111'],
        ['DESCUENTOSLEGALES', 2, 'AFP + SALUD + SEGUROCESANTIA', null, 0, 0, 0, '111111111111'],
        ['RENTAIMPONIBLESD', 1, "RTMN + IMPONIBLEYNOIMPUTABLE", null, 0, 0, 0, '111111111111'],
        ['RENTAIMPONIBLESD', 2, "SUELDOBASE", null, 0, 0, 0, '111111111111'],
        ['DESCUENTOSVOLUNTARIOS', 1, "ADICIONALSALUD + APV + AFPOTRO + ISAPREOTRO", null, 0, 0, 0, '111111111111'],
        ['DESCUENTOSVOLUNTARIOS', 2, "ADICIONALSALUD + APV + AFPOTRO + ISAPREOTRO", null, 0, 0, 0, '111111111111'],
        ['TOPE30HORAS', 1, 'CARGAHORARIA', null, 0, 30, 30, '111111111111'],
        ['TOPE30HORAS', 2, 'CARGAHORARIA', null, 0, 30, 30, '111111111111'],
        ['SUMACARGAS', 1, 'CARGAHORARIA', null, 0, 0, 0, '111111111111'],
        ['SUMACARGAS', 2, 'CARGAHORARIA', null, 0, 0, 0, '111111111111'],
        ['REMUNERACIONTRIBUTABLE', 1, 'RENTAIMPONIBLE - DESCUENTOSLEGALES', 'UF', 0, 60, 60, '111111111111'],
        ['REMUNERACIONTRIBUTABLE', 2, 'RENTAIMPONIBLE - DESCUENTOSLEGALES', 'UF', 0, 60, 60, '111111111111'],
        ['IMPUESTORENTA', 1, 'IMPUESTOUNICO - REBAJAIMPUESTO', null, 0, 0, 0, '111111111111'],
        ['IMPUESTORENTA', 2, 'IMPUESTOUNICO - REBAJAIMPUESTO', null, 0, 0, 0, '111111111111'],
        ['IMPUESTOUNICO', 1, "IMPUESTOTRAMO2 / IMPUESTOTRAMO2 * FACTORIMPTRAMO2 M+ IMPUESTOTRAMO3 / IMPUESTOTRAMO3 * FACTORIMPTRAMO3 M+ IMPUESTOTRAMO4 / IMPUESTOTRAMO4 * FACTORIMPTRAMO4 M+ IMPUESTOTRAMO5 / IMPUESTOTRAMO5 * FACTORIMPTRAMO5 M+ IMPUESTOTRAMO6 / IMPUESTOTRAMO6 * FACTORIMPTRAMO6 M+ IMPUESTOTRAMO7 / IMPUESTOTRAMO7 * FACTORIMPTRAMO7 M+ IMPUESTOTRAMO8 / IMPUESTOTRAMO8 * FACTORIMPTRAMO8 M+ MR * REMUNERACIONTRIBUTABLE",
            null, 0, 0, 0, '111111111111'],
        ['IMPUESTOUNICO', 2, 'IMPUESTOTRAMO2 / IMPUESTOTRAMO2 * FACTORIMPTRAMO2 M+ IMPUESTOTRAMO3 / IMPUESTOTRAMO3 * FACTORIMPTRAMO3 M+ IMPUESTOTRAMO4 / IMPUESTOTRAMO4 * FACTORIMPTRAMO4 M+ IMPUESTOTRAMO5 / IMPUESTOTRAMO5 * FACTORIMPTRAMO5 M+ IMPUESTOTRAMO6 / IMPUESTOTRAMO6 * FACTORIMPTRAMO6 M+ IMPUESTOTRAMO7 / IMPUESTOTRAMO7 * FACTORIMPTRAMO7 M+ IMPUESTOTRAMO8 / IMPUESTOTRAMO8 * FACTORIMPTRAMO8 M+ MR * REMUNERACIONTRIBUTABLE', null, 0, 0, 0, '111111111111'],
        ['FILTROCONTRATOFIJO', 1, '1 - ADHIEREASEGURO * TIPOCONTRATO', null, 2, 2, 0, '111111111111'],
        ['FILTROCONTRATOFIJO', 2, '1 - ADHIEREASEGURO * TIPOCONTRATO', null, 2, 2, 0, '111111111111'],
        ['FILTROCONTRATOINDEF', 1, '1 - ADHIEREASEGURO * TIPOCONTRATO', null, 1, 1, 0, '111111111111'],
        ['FILTROCONTRATOINDEF', 2, '1 - ADHIEREASEGURO * TIPOCONTRATO', null, 1, 1, 0, '111111111111'],
        ['REBAJAIMPUESTO', 1, 'IMPUESTOTRAMO2  / IMPUESTOTRAMO2 * FACTORREBAJAIMPTRAMO2 M+ IMPUESTOTRAMO3  / IMPUESTOTRAMO3 * FACTORREBAJAIMPTRAMO3 M+ IMPUESTOTRAMO4  / IMPUESTOTRAMO4 * FACTORREBAJAIMPTRAMO4 M+ IMPUESTOTRAMO5  / IMPUESTOTRAMO5 * FACTORREBAJAIMPTRAMO5 M+ IMPUESTOTRAMO6  / IMPUESTOTRAMO6 * FACTORREBAJAIMPTRAMO6 M+ IMPUESTOTRAMO7  / IMPUESTOTRAMO7 * FACTORREBAJAIMPTRAMO7 M+ IMPUESTOTRAMO8  / IMPUESTOTRAMO8 * FACTORREBAJAIMPTRAMO8 M+ MR ', null, 0, 0, 0, '111111111111'],
        ['REBAJAIMPUESTO', 2,
            "IMPUESTOTRAMO2 / IMPUESTOTRAMO2 * FACTORREBAJAIMPTRAMO2 M+ IMPUESTOTRAMO3 / IMPUESTOTRAMO3 * FACTORREBAJAIMPTRAMO3 M+ IMPUESTOTRAMO4 / IMPUESTOTRAMO4 * FACTORREBAJAIMPTRAMO4 M+ IMPUESTOTRAMO5 / IMPUESTOTRAMO5 * FACTORREBAJAIMPTRAMO5 M+ IMPUESTOTRAMO6 / IMPUESTOTRAMO6 * FACTORREBAJAIMPTRAMO6 M+ IMPUESTOTRAMO7 / IMPUESTOTRAMO7 * FACTORREBAJAIMPTRAMO7 M+ IMPUESTOTRAMO8 / IMPUESTOTRAMO8 * FACTORREBAJAIMPTRAMO8 M+ MR",
            null, 0, 0, 0, '111111111111'],
        ['SEGUROCESANTIA', 1, 'FILTROCONTRATOINDEF / FILTROCONTRATOINDEF * 0.006 * RENTAIMPONIBLE M+ FILTROCONTRATOFIJO / FILTROCONTRATOFIJO * 0.03 * RENTAIMPONIBLE M+ MR', null, 0, 0, 0, '111111111111'],
        ['SEGUROCESANTIA', 2,
            "FILTROCONTRATOINDEF / FILTROCONTRATOINDEF * 0.006 * RENTAIMPONIBLE M+ FILTROCONTRATOFIJO / FILTROCONTRATOFIJO * 0.03 * RENTAIMPONIBLE M+ MR",
            null, 0, 0, 0, '111111111111'],
        ['ASIGNACIONFAMILIAR', 1,
            "FILTROASIGFAMT1 / FILTROASIGFAMT1 * ASIGCAR.FAMTRAMO1 M+ FILTROASIGFAMT2 / FILTROASIGFAMT2 * ASIGCAR.FAMTRAMO2 M+ FILTROASIGFAMT3 / FILTROASIGFAMT3 * ASIGCAR.FAMTRAMO3 M+ MR * CARGASFAMILIARES",
            null, 0, 0, 0, '111111111111'],
        ['ASIGNACIONFAMILIAR', 2, 'FILTROASIGFAMT1 / FILTROASIGFAMT1 * ASIGCAR.FAMTRAMO1 M+ FILTROASIGFAMT2 / FILTROASIGFAMT2 * ASIGCAR.FAMTRAMO2 M+ FILTROASIGFAMT3 / FILTROASIGFAMT3 * ASIGCAR.FAMTRAMO3 M+ MR * CARGASFAMILIARES', null, 0, 0, 0, '111111111111'],
        ['LICENCIA', 1, 'RENTAIMPONIBLESD / CARGAHORARIA / 4 * HORASLICENCIA', null, 0, 0, 0, '111111111111'],
        ['LICENCIA', 2, 'RENTAIMPONIBLESD / 30 * DIASLICENCIA', null, 0, 0, 0, '111111111111'],
        ['ADICIONALSALUD', 1, 'COTIZACIONPACTADA - SALUD', null, 0, 0, 0, '111111111111'],
        ['ADICIONALSALUD', 2, 'COTIZACIONPACTADA - SALUD', null, 0, 0, 0, '111111111111'],
        ['INASISTENCIA', 1, 'RENTAIMPONIBLESD / CARGAHORARIA / 4 * HORASINASISTENCIA', null, 0, 0, 0, '111111111111'],
        ['INASISTENCIA', 2, 'RENTAIMPONIBLESD / 30 * 7 / CARGAHORARIA * HORASINASISTENCIA', null, 0, 0, 0, '111111111111'],
        ['IMPONIBLEYNOIMPUTABLE', 1, "HORASPERFECCIONAMIENTO", null, 0, 0, 0, '111111111111'],
        ['TOTALNOIMPONIBLE', 1, 'ASIGNACIONFAMILIAR + EXCEDENTEBONOSAELEY19410Y19933', null, 0, 0, 0, '111111111111'],
        ['TOTALNOIMPONIBLE', 2, 'ASIGNACIONFAMILIAR', null, 0, 0, 0, '111111111111'],
        ['TOTALHABERES', 1, 'RENTAIMPONIBLE + TOTALNOIMPONIBLE', null, 0, 0, 0, '111111111111'],
        ['TOTALHABERES', 2, 'RENTAIMPONIBLE + TOTALNOIMPONIBLE', null, 0, 0, 0, '111111111111'],
        ['RTMN', 1, 'IMPONIBLEEIMPUTABLE + PLANILLACOMPLEMENTARIA', null, 0, 0, 0, '111111111111'],
        ['IMD', 1, 'VALORIMD * CARGAHORARIA', null, 0, 0, 0, '111111111111'],
        ['RENTAIMPONIBLE', 1, 'RENTAIMPONIBLESD', null, 0, 0, 0, '111111111111'],
        ['RENTAIMPONIBLE', 2, 'RENTAIMPONIBLESD', null, 0, 0, 0, '111111111111'],
        ['SUELDOBASE', 2, 'SUELDOBASEB * FACTORASIST', null, 0, 0, 0, '111111111111'],
        ['TOTALDESCUENTOS', 1, 'DESCUENTOSLEGALES + DESCUENTOSVOLUNTARIOS + IMPUESTORENTA', null, 0, 0, 0, '111111111111'],
        ['TOTALDESCUENTOS', 2, 'DESCUENTOSLEGALES + DESCUENTOSVOLUNTARIOS + IMPUESTORENTA', null, 0, 0, 0, '111111111111'],
        ['SUMACARGASTODOS', 1, 'CARGAHORARIA', null, 0, 0, 0, '111111111111'],
        ['SUMACARGASTODOS', 2, 'CARGAHORARIA', null, 0, 0, 0, '111111111111'],
    ],

    'tuitions'   => [
        ['TOTALAPAGAR', 'Total a Pagar', 'O', 1, 0],
        ['RENTAIMPONIBLE', 'Renta Imponible', 'O', 1, 0],
        ['FACTORRBMNBASICA', 'Factor RMBN Basica', 'P', 0, 1],
        ['CARGAHORARIA', 'Carga horaria', 'P', 0, 0],
        ['DESCUENTOSLEGALES', 'Descuentos previsionales', 'O', 1, 0],
        ['AFP', 'AFP', 'O', 1, 0],
        ['SALUD', 'Salud', 'O', 1, 0],
        ['COTIZACIONPACTADA', 'Cotización pactada', 'P', 0, 0],
        ['AFPTRABAJADOR', 'AFP Trabajador', 'P', 0, 0],
        ['IMPUESTOUNICO', 'Impuesto Único', 'O', 1, 0],
        ['REBAJAIMPUESTO', 'Rebaja Impuesto', 'O', 1, 0],
        ['REMUNERACIONTRIBUTABLE', 'Remuneración tributable', 'O', 1, 0],
        ['IMPUESTORENTA', 'Impuesto Renta', 'O', 1, 0],
        ['CARGASFAMILIARES', 'Cargas Familiares Trabajador', 'P', 0, 0],
        ['TIPOCONTRATO', 'Tipo contrato', 'P', 0, 0],
        ['YEARINICIOSERVICIO', 'YEARINICIOSERVICIO', 'P', 0, 0],
        ['APV', 'APV', 'P', 1, 0],
        ['SEGUROCESANTIA', 'Seguro cesantia', 'O', 1, 0],
        ['HORASPERFECCIONAMIENTO', 'Horas perfeccionamiento', 'P', 1, 1],
        ['SUMACARGAS', 'Suma Cargas', 'S', 0, 0],
        ['YEARACTUAL', 'YEARACTUAL', 'P', 0, 0],
        ['SUELDOBASE', 'Sueldo Base', 'O', 1, 0],
        ['EXCEDENTEBONOSAELEY19410Y19933', 'Excedente Bono SAE ley 19410/19933', 'O', 1, 0],
        ['UTM', 'Valor UTM', 'P', 0, 0],
        ['UF', 'Valor UF', 'P', 0, 0],
        ['DESCUENTOSVOLUNTARIOS', 'Descuentos voluntarios', 'O', 1, 0],
        ['TOPE30HORAS', 'TOPE30HORAS', 'O', 0, 0],
        ['FILTROCONTRATOFIJO', 'FILTROCONTRATOFIJO', 'O', 0, 0],
        ['FILTROCONTRATOINDEF', 'FILTROCONTRATOINDEF', 'O', 0, 0],
        ['ASIGNACIONFAMILIAR', 'Asignacion familiar', 'O', 1, 0],
        ['LICENCIA', 'Licencia médica', 'O', 1, 0],
        ['COSTOHORALICENCIADOCENTE', 'Costo por hora de licencia para docentes', 'P', 0, 1, 8],
        ['COSTODIALICENCIANODOCENTE', 'Costo por día de licencia para no docentes', 'P', 0, 1, 8],
        ['COSTOHORAINASISTENCIADOCENTE', 'Costo por hora de inasistencia docente', 'P', 0, 0],
        ['COSTOHORAINASISTENCIANODOCENTE', 'Costo por hora de inasistencia no docente', 'P', 0, 0],
        ['DIASLICENCIA', 'Días licencia no docente', 'P', 0, 0],
        ['COTIZACIONISAPRE', 'Cotización en isapre', 'P', 0, 0],
        ['COTIZACIONAFP', 'Cotización AFP del trabajador', 'P', 0, 0],
        ['CIERREMES', 'Día del cierre de mes', 'P', 0, 1],
        ['UFAFP', 'Valor UF aplicable a afps', 'P', 0, 0],
        ['UFINP', 'Valor UF aplicable al INP', 'P', 0, 0],
        ['ADICIONALSALUD', 'Adicional de salud', 'O', 1, 1],
        ['AFPOTRO', 'Otros descuentos previsionales', 'P', 1, 1],
        ['ISAPREOTRO', 'Otros descuentos en salud', 'P', 1, 1],
        ['HORASLICENCIA', 'Horas licencia docente', 'P', 0, 0],
        ['HORASINASISTENCIA', 'Horas de inasistencia', 'P', 0, 0],
        ['INASISTENCIA', 'Inasistencia', 'O', 1, 0],
        ['PLANILLACOMPLEMENTARIA', 'Planilla complementaria', 'O', 1, 1],
        ['RTMN', 'R.T.M.N', 'O', 1, 0],
        ['IMPONIBLEYNOIMPUTABLE', 'Imponible y No imputable a la R.T.M.N.', 'O', 1, 0],
        ['TOTALNOIMPONIBLE', 'Total no imponible', 'O', 1, 0],
        ['TOTALHABERES', 'Total Haberes', 'O', 1, 0],
        ['TOTALDESCUENTOSPREVISIONALES', 'Total Dctos Previsionales', 'O', 1, 0],
        ['ADHIEREASEGURO', 'Si adhiere o no a seguro de cesantia', 'P', 0, 0],
        ['DIASTRABAJADOS', 'Días trabajados', 'P', 1, 1],
        ['DIASNOTRABAJADOS', 'Días de Ausencia', 'P', 1, 1],
        ['IMPONIBLEEIMPUTABLE', 'Imponible e imputable a la RTMN', 'O', 1, 1],
        ['VALORIMD', 'Valor IMD', 'P', 0, 0],
        ['IMD', 'IMD', 'O', 0, 0],
        ['SUMACARGASTODOS', 'Suma carga todos los trabajadores', 'S', 0, 0],
        ['RENTAIMPONIBLESD', 'Renta imponible sin descuentos', 'O', 0, 0],
        ['FACTORASIST', 'Factor de asistencia y licencia medica', 'P', 0, 0],
        ['SUELDOBASEB', 'Sueldo base bruto', 'P', 0, 0],
        ['TOTALDESCUENTOS', 'Total Descuentos', 'O', 1, 0],
    ],

    'templates'  => [
        Worker::WORKER_TYPE_TEACHER     => [
            ['TEX', 'Imponible e imputable a la RTMN', 0, 0],
            ['NV', 'RBMN', 0, 0],
            ['NV', 'UMP', 0, 0],
            ['NV', 'Ley 19410', 0, 0],
            ['NV', 'Ley 19933', 1, 0],
            ['NV', 'Perfeccionamiento', 0, 0],
            ['NV', 'Asignacion Voluntaria', 0, 0],
            ['NV', 'Desempeño dificil', 0, 0],
            ['NV', 'Inasistencia', 1, 0],
            ['NV', 'Licencia médica', 1, 0],
            ['_L_', '', 0, 0],
            ['NV', 'Renta Imponible', 0, 0],
            ['NV', 'Asignacion familiar', 0, 0],
            [null, '', 0, 0],
            ['NVV', 'Total Haberes', 0, 0],
            ['NV', 'AFP', 0, 0],
            ['NV', 'SALUD', 0, 0],
            ['NV', 'Adicional de salud', 1, 0],
            ['NV', 'Seguro cesantia', 0, 0],
            ['NV', 'Descuentos previsionales', 0, 1],
            ['TEX', 'Calculo de Imp. a la Renta', 0, 0],
            ['NV', 'Remuneración tributable', 0, 0],
            ['NV', 'Impuesto Renta', 0, 1],
            ['NV', 'APV', 1, 0],
            ['NV', 'Colegio de profesores', 1, 0],
            ['NV', 'Fundacion Lopez Perez', 1, 0],
            ['NV', 'Prestamo Social Caja los Andes', 1, 0],
            ['NV', 'Prestamo Social Caja los heroes', 1, 0],
            ['NV', 'Otros', 1, 0],
            [null, '', 0, 0],
            ['_L_', '', 0, 0],
            ['NV', 'Descuentos voluntarios', 0, 1],
            ['NVV', 'Total Descuentos', 0, 1],
            ['__L', '', 0, 0],
            ['N V', 'Total a Pagar', 0, 0],
        ],
        Worker::WORKER_TYPE_NON_TEACHER => [
            ['NV', 'Sueldo Base', 0, 0],
            ['NV', 'Asignacion Voluntaria', 1, 0],
            ['NV', 'Desempeño dificil', 0, 0],
            ['NV', 'Ley 19464', 0, 0],
            ['NV', 'Inasistencia', 1, 0],
            ['_L_', '', 0, 0],
            ['NV', 'Renta Imponible', 0, 0],
            ['NV', 'Asignacion familiar', 0, 0],
            ['NV', 'Total no imponible', 1, 0],
            ['_L_', '', 0, 0],
            ['NVV', 'Total Haberes', 0, 0],
            ['NV', 'AFP', 0, 0],
            ['NV', 'Seguro cesantia', 1, 0],
            ['NV', 'SALUD', 0, 0],
            ['_L_', '', 0, 0],
            ['NV', 'Descuentos previsionales', 0, 1],
            [null, '', 0, 0],
            ['TEX', 'Calculo de Imp. a la Renta', 0, 0],
            ['NV', 'Renta Imponible', 0, 0],
            ['NV', 'Descuentos previsionales', 0, 0],
            [null, '', 0, 0],
            ['_L_', '', 0, 0],
            ['NV', 'Remuneración tributable', 0, 0],
            ['NV', 'Impuesto Único', 0, 0],
            ['NV', 'Rebaja Impuesto', 0, 0],
            ['_L_', '', 0, 0],
            ['NV', 'Impuesto Renta', 0, 1],
            ['NV', 'APV', 1, 0],
            ['NV', 'Adicional de salud', 1, 0],
            [null, '', 0, 0],
            ['NV', 'Prestamo Social Caja los Andes', 1, 0],
            ['NV', 'Prestamo Social Caja los heroes', 1, 0],
            ['NV', 'Cuenta Ahorro Caja los Andes', 1, 0],
            ['NV', 'Fundacion Lopez Perez', 1, 0],
            ['_L_', '', 0, 0],
            ['NV', 'Descuentos voluntarios', 0, 1],
            ['NV', 'Total Descuentos', 0, 1],
            ['_L_', '', 0, 0],
            ['NV', 'Total a Pagar', 0, 0],
        ],
    ],
];
